drop table if exists 	class,
			student,
			headman,
			teacher,
			class_teacher,
			roles,
			teacher_roles,
			news,
			news_author,
			subject,
			teacher_subject,
			schedule,
			schedule_of_subject,
			subject_of_class;
